extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - prettier

env:
  browser: true
  es2021: true

parserOptions:
  sourceType: module
  ecmaVersion: 12 # default for env.es2021, but needed for vue-eslint-parser

ignorePatterns:
  - .github
  - dist
  - __tests__

rules:
  curly: error
  eqeqeq: error
  object-shorthand: error
  prefer-const: error
