# build stage ------------------------------------------------------
FROM node:lts AS builder

WORKDIR /buildstage
COPY . .
RUN yarn install
RUN npx togostanza build

# prod stage -------------------------------------------------------
FROM nginx:alpine
RUN apk --no-cache add ca-certificates
ARG PATH_NGINX_DOCUMENT_ROOT
COPY --from=builder /buildstage/dist $PATH_NGINX_DOCUMENT_ROOT
